### ISSUE TITLE
Would it be possible to release a 5.7 package?

### ISSUE THREAD

**Issue by meleu** [leokhoa/quick-create-laravel#1]
Pretty much what the title says. :)

**Comment by leokhoa** [comment]
@meleu : Sure, no problem :)

**Comment by meleu** [comment]
awesome, I've just saw you already did it. Thanks!

closing this issue.

by the way, do you have some donation system?

**Comment by leokhoa** [comment]
@meleu : Could you please donate me 1 star :)
https://github.com/leokhoa/laragon
